coverage_service: coveralls
xcodeproj: ./Authentication.xcodeproj
ci_service: travis_pro
scheme: Authentication
coverage_access_token: 70TniiTKCtcXa8J6oDCmWG9MYkVrsJCQW
ignore:
  - AuthenticationTests/*
